import Link from "next/link";
import { vehicles } from "@/data/vehicles";
import { getCatalogueVariants } from "@/data/vehicle-variant-catalogue";
import { summarizeTrips, type Trip } from "@/lib/community-range";
import { communityEnabled } from "@/lib/community-range-server";
import { prisma } from "@/lib/prisma";
import TripForm from "./TripForm";
export const dynamic = "force-dynamic";
export const metadata = { title: "Indian community EV efficiency | PlugV", description: "Reviewed owner trip reports, measured energy efficiency and clearly labelled battery-percentage extrapolations.", alternates: { canonical: "/community-range" } };
export default async function CommunityRangePage() {
  let enabled = communityEnabled(); let results: ReturnType<typeof summarizeTrips> = [];
  if (enabled) { try { const rows = await prisma.communityTrip.findMany({where:{status:"APPROVED",createdAt:{gte:new Date(Date.now()-90*86400000)}},select:{contributor:true,payload:true}}); results = summarizeTrips(rows.map(r=>({contributor:r.contributor,payload:r.payload as Trip}))); } catch { enabled = false; } }
  return <main className="mx-auto max-w-5xl px-5 py-12 text-slate-100"><h1 className="text-4xl font-bold">Indian real-world EV efficiency</h1><p className="mt-4">Help build a community evidence base for city traffic, highway travel, heat, hills and AC use in India. These are reviewed owner reports, not laboratory tests or independently verified vehicle records.</p><section className="mt-8 space-y-3"><h2 className="text-2xl">How the efficiency index works</h2><p>We show energy per 100 km (lower uses less energy), rather than an arbitrary score. Dashboard energy and charger energy have separate results: charger readings include charging losses. Battery-percentage reports show an extrapolated full-charge distance, not measured efficiency or a promised driving range.</p><p>Each group matches model, variant, model year, road type, temperature, average speed, AC, occupants, terrain and measurement method. It needs at least five approved trips from three contributor browsers within 90 days. A browser is not a verified person or vehicle; clearing cookies can create a new contributor.</p><p>We average each contributor’s trips, then report the median of those averages so frequent submissions do not dominate. The spread is the lowest to highest contributor average, not a statistical confidence interval. Sparse groups remain unpublished. No community data changes trip-planner estimates automatically.</p><p>Source: owner-submitted trip readings, manually reviewed for consistency. Review cannot establish authenticity. <Link className="underline" href="/methodology">PlugV methodology</Link> · <Link className="underline" href="/travel">Plan a trip</Link> · <Link className="underline" href="/vehicles">Explore EVs</Link></p></section><section className="mt-8"><h2 className="text-2xl">Reviewed community results</h2>{results.length === 0 ? <p>No eligible community groups yet. We will not fill this space with estimates or invented owner results.</p> : results.map((r,i)=><article key={i} className="my-4 rounded border border-slate-600 p-4"><h3 className="text-xl"><Link className="underline" href={`/vehicles/${r.conditions.slug}`}>{r.conditions.slug}</Link> · {r.conditions.variant} · {r.conditions.modelYear}</h3><p>{r.conditions.road} · {r.conditions.temperature} · {r.conditions.speed} · AC {r.conditions.ac} · {r.conditions.passengers} occupants · {r.conditions.terrain}</p><p>{r.conditions.method}: {r.median.toFixed(1)} {r.conditions.method === "Battery percentage" ? "km extrapolated" : "kWh/100 km"} · spread {r.low.toFixed(1)}–{r.high.toFixed(1)}</p><p>{r.trips} reviewed trips · {r.contributors} contributor browsers · latest trip {r.latest}. Self-reported, not independently verified.</p></article>)}</section><TripForm enabled={enabled} options={vehicles.map(v=>({slug:v.slug,label:v.slug.replaceAll("-"," "),variants:getCatalogueVariants(v.slug)})).filter(v=>v.variants.length > 0)}/></main>;
}
