import Link from "next/link";
import { ArrowRight, BookOpen, Calculator, CheckCircle2 } from "lucide-react";
import SiteHeader from "@/components/home/SiteHeader";
import SiteFooter from "@/components/home/SiteFooter";
import { knowledgeArticles } from "@/data/knowledge-articles";

export default function KnowledgeHubPage() {
  return <main className="min-h-screen bg-slate-950 text-white"><SiteHeader /><section className="relative overflow-hidden border-b border-white/10"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_15%_20%,rgba(56,189,248,0.2),transparent_32%),radial-gradient(circle_at_85%_70%,rgba(16,185,129,0.12),transparent_30%)]" /><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24 lg:px-8"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-sky-300/20 bg-sky-300/10 px-4 py-2 text-xs font-semibold uppercase tracking-[0.2em] text-sky-200"><BookOpen className="h-4 w-4" />PlugV Knowledge Hub</div><h1 className="mt-7 text-4xl font-semibold tracking-[-0.045em] sm:text-6xl">Understand EVs.<span className="block text-sky-300">Make a better decision.</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-300 sm:text-lg">Practical India-focused guides and transparent calculators for buying, charging and owning an electric car—without hype or hidden assumptions.</p><div className="mt-8 flex flex-wrap gap-3 text-sm text-slate-300"><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300" />Source-labelled</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-300" />Reviewed for freshness</span><span className="inline-flex items-center gap-2"><Calculator className="h-4 w-4 text-sky-300" />Interactive tools</span></div></div></div></section><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{knowledgeArticles.map((article) => <Link key={article.slug} href={`/knowledge/${article.slug}`} className="group rounded-[2rem] border border-white/10 bg-white/[0.04] p-6 transition hover:-translate-y-1 hover:border-sky-300/25 hover:bg-white/[0.06]"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-sky-300/10 px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.16em] text-sky-300">{article.category}</span><span className="text-xs text-slate-500">{article.readTime}</span></div><h2 className="mt-5 text-2xl font-semibold tracking-tight text-white">{article.shortTitle}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{article.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-sky-300">Read guide <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link>)}</div></section><SiteFooter /></main>;
}
