import type { Metadata } from "next";
import LegalPage from "@/components/legal/LegalPage";

export const metadata: Metadata = { title: "Privacy Policy", description: "How PlugV handles information when you use its EV discovery, charging, travel and ownership tools.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <LegalPage eyebrow="Your privacy" title="Privacy Policy" summary="This policy explains what information PlugV may process, why it is used, and the choices available to you when using plugv.in.">
    <p><strong>Effective date:</strong> 26 August 2026 · <strong>Last updated:</strong> 28 August 2026</p>
    <h2>1. Operator and scope</h2><p>This policy applies to visitors and users of PlugV.in. PlugV is an India-focused electric-vehicle information and planning platform operated by Syed Manjoor Ahmed, trading under the name PlugV, from Sun City, Bandlaguda Jagir, Hyderabad, Telangana, India.</p>
    <h2>2. Information you provide</h2><p>You may provide information when contacting PlugV, reporting incorrect data, saving owner reminders, using search or entering trip details. Do not submit sensitive personal, financial or medical information through free-text fields.</p>
    <h2>3. Owner tools and email reminders</h2><p>Saved trips, saved chargers, alert preferences and device-only reminders are stored in your browser using local storage. Clearing browser data may permanently remove them. If you separately activate email reminders, PlugV stores your verified email address, consent record, reminder type, title, due date and notice period on its server so the requested email can be delivered. This information is not used for marketing.</p>
    <h2>4. Email reminder choices</h2><p>Email ownership is confirmed through a time-limited verification link. Reminder emails include an unsubscribe link. Deleting an email reminder removes that reminder from active delivery. Unsubscribing disables all active email reminders. You may request access or deletion by contacting support@plugv.in.</p>
    <h2>5. Email service providers</h2><p>PlugV uses hosting, database and email-delivery providers, currently including Vercel, Neon and Zoho Mail, only as necessary to operate this feature. Access credentials are kept outside the public website code.</p>
    <h2>6. Location information</h2><p>PlugV requests device location only when you choose a feature such as “Use my location.” Your browser controls permission. Location is used to calculate nearby charging results or routes and may be sent to mapping, geocoding or routing providers needed to return that result.</p>
    <h2>7. Technical and usage information</h2><p>Hosting and security providers may process standard technical logs such as IP address, browser type, requested URL, timestamps, device information and error diagnostics. PlugV may use privacy-conscious analytics to understand reliability and improve features. We do not sell personal information.</p>
    <h2>8. External service providers</h2><p>PlugV relies on infrastructure and mapping services such as Vercel, map providers, OpenStreetMap-based geocoding or routing services, and email providers. Their processing is governed by their own policies. Only the information reasonably required to provide the requested feature should be sent.</p>
    <h2>9. Cookies</h2><p>PlugV may use essential cookies or similar storage for security, preferences and core functionality. If non-essential analytics or advertising cookies are introduced, PlugV will provide appropriate notice and choices where required.</p>
    <h2>10. Retention and security</h2><p>Information is retained only as reasonably needed for the relevant purpose, legal obligations, security or dispute resolution. PlugV uses reasonable safeguards, but no online service can promise absolute security.</p>
    <h2>11. Your choices and rights</h2><p>You may request access to, correction of or deletion of personal information associated with you, withdraw reminder consent, or raise a grievance by emailing <a href="mailto:support@plugv.in?subject=Privacy%20request">support@plugv.in</a>. You can also deny location permission, clear local browser storage or stop using the service. PlugV will acknowledge and address valid requests in accordance with applicable Indian law.</p>
    <h2>12. Children</h2><p>PlugV is not designed to collect personal information from children. A parent or guardian should supervise use by anyone who cannot legally consent to data processing.</p>
    <h2>13. Grievance contact</h2><p>Privacy questions and grievances may be sent to the PlugV Grievance Contact at <a href="mailto:support@plugv.in?subject=Privacy%20grievance">support@plugv.in</a>, with correspondence addressed to PlugV, Sun City, Bandlaguda Jagir, Hyderabad, Telangana, India. Include enough information to identify the issue without sending unnecessary sensitive information.</p>
    <h2>14. Updates</h2><p>We may update this policy as PlugV develops. Material changes will be reflected by a new last-updated date on this page.</p>
  </LegalPage>;
}
