// Compile TypeScript in this audit process, without a dev server or external AI.
import { createRequire } from 'node:module';
import Module from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const ts = require('typescript');
const resolve = Module._resolveFilename;
Module._resolveFilename = function(id, ...args) { return resolve.call(this, id.startsWith('@/') ? path.join(process.cwd(), id.slice(2)) : id, ...args); };
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true }}).outputText, filename);
const {answerWithPlugV, findMentionedVehicles} = require('../lib/assistant/smartAssistant.ts');
const {parseAssistantPrompt} = require('../lib/assistant/recommendationEngine.ts');
let passed = 0;
function check(name, test) { try { test(); passed++; console.log(`PASS ${name}`); } catch(error) { console.error(`FAIL ${name}: ${error.message}`); process.exitCode = 1; } }
const reply = (q, previous) => answerWithPlugV(q, previous);
const noPicks = (q) => assert.equal(reply(q).recommendations, undefined);
check('short names and typo correction', () => assert.equal(findMentionedVehicles('Comapre Nexon and maindra BE6').length, 2));
check('no substring collision', () => assert.deepEqual(findMentionedVehicles('BYD Sealion 7').map(v=>v.slug), ['byd-sealion-7']));
check('short model name i7', () => assert.equal(findMentionedVehicles('BMW i7 price')[0].slug, 'bmw-i7'));
check('same car cannot compare to itself', () => assert.match(reply('Compare Nexon vs Nexon').text, /two different/));
check('comparison keeps charging label correct', () => assert.doesNotMatch(reply('compare Nexon vs BE6').text, /Power \/ battery/));
check('direct price lookup', () => { const r=reply('Nexon price'); assert.match(r.text, /Nexon/); assert.equal(r.recommendations, undefined); assert.ok(r.actions.some(a=>a.href.startsWith('https:'))); });
for (const q of ['EV under ₹20 lakh', 'EV under Rs 20,00,000', 'EV under INR 2000000', 'EV budget 20 lacs']) check(q, () => assert.equal(parseAssistantPrompt(q).budgetLakh, 20));
check('crore budget', () => assert.equal(parseAssistantPrompt('EV under 1.5 crore').budgetLakh, 150));
check('km is not a budget', () => assert.equal(parseAssistantPrompt('EV range under 500 km').budgetLakh, undefined));
check('launched is not upcoming', () => assert.equal(parseAssistantPrompt('newly launched EVs').scope, 'launched'));
check('all EVs does not imply upcoming', () => assert.equal(parseAssistantPrompt('all EVs').scope, 'launched'));
check('upcoming scope', () => assert.equal(parseAssistantPrompt('upcoming EVs').scope, 'upcoming'));
check('greeting does not swallow request', () => {const r=reply('Hi find a Tata EV under 20 lakh');assert.ok(r.recommendations?.length);assert.ok(r.recommendations.every(x=>x.vehicle.brand==='Tata'));});
check('brand exclusion', () => { const r=reply('Find EVs under 25 lakh excluding Tata'); assert.ok(r.recommendations?.length); assert.ok(r.recommendations.every(x=>x.vehicle.brand!=='Tata')); });
check('impossible budget not relaxed', () => noPicks('Find EV under 1 lakh'));
check('unsupported seating asks clarification', () => {noPicks('find a 7 seater EV');assert.match(reply('find a 7 seater EV').text, /cannot reliably/);});
check('unrelated input no random recommendations', () => noPicks('write a poem about mangoes'));
check('nonsense no random recommendations', () => noPicks('asdfgh'));
check('empty input', () => noPicks(''));
check('plural chargers handled', () => assert.ok(reply('find fast chargers near me').actions.some(a=>a.href==='/charging')));
check('reservation not promised', () => assert.match(reply('reserve a charger in Hyderabad').text, /cannot hold/));
check('home charging is not station search', () => assert.ok(reply('home charger installation').actions.every(a=>a.href.startsWith('/knowledge'))));
check('route without km requests route planner', () => assert.ok(reply('plan a route from Hyderabad to Bangalore').actions.some(a=>a.href==='/travel')));
check('missing battery never assumed', () => assert.match(reply('Can Nexon cover 180 km?').text, /starting battery percentage/));
check('missing variant never assumes longest', () => assert.match(reply('Can Tiago EV cover 180 km at 90%?').text, /specify a recorded battery/));
check('explicit smaller variant used', () => {const r=reply('Can Tiago EV 19.2 kWh cover 180 km at 90%?');assert.match(r.text, /19.2 kWh/);assert.match(r.text, /insufficient/);assert.doesNotMatch(r.text, /arrival battery: 0%/);});
check('explicit larger variant used', () => assert.match(reply('Can Tiago EV 24 kWh cover 100 km at 90%?').text, /24 kWh/));
check('invalid percentage rejected', () => assert.match(reply('Can Nexon cover 180 km at 150%?').text, /between 0% and 100%/));
check('negative percentage rejected', () => assert.match(reply('Can Nexon cover 180 km at -5%?').text, /between 0% and 100%/));
check('zero distance rejected', () => assert.match(reply('Can Nexon cover 0 km at 90%?').text, /positive journey distance/));
check('variant not in profile rejected', () => assert.match(reply('Can Nexon 99 kWh cover 180 km at 90%?').text, /specify a recorded battery/));
check('trip numbers remain estimates', () => assert.match(reply('Can Nexon 45 kWh cover 180 km at 90%?').text, /not manufacturer-verified/));
check('single model follow-up', () => assert.match(reply('what is its price?', 'Tell me about Nexon').text, /Nexon/));
check('ambiguous follow-up', () => assert.match(reply('what is its price?', 'compare Nexon and BE6').text, /Which EV/));
check('upcoming links are valid route family', () => assert.ok(reply('Tell me about Eva').actions.some(a=>a.href==='/upcoming/vayve-mobility-eva')));
check('long input bounded', () => noPicks('EV '.repeat(1000)));
check('unknown model lookup asks name', () => assert.match(reply('What is the price of Tesla Model 3?').text, /could not identify that model/));
check('minimum budget is not maximum', () => noPicks('EV above 20 lakh'));
check('budget interval is not ignored', () => noPicks('EV between 10 and 20 lakh'));
check('negative budget rejected', () => noPicks('EV under -5 lakh'));
check('newest ranking needs launch dates', () => noPicks('newest EVs'));
check('multiple excluded brands', () => { const r=reply('Find EVs excluding Tata and Mahindra under 25 lakh'); assert.ok(r.recommendations?.length); assert.ok(r.recommendations.every(x=>!['Tata','Mahindra'].includes(x.vehicle.brand))); });
check('contracted brand exclusion', () => assert.ok(parseAssistantPrompt("Find EVs, I don't want Tata").excludedBrands.includes('Tata')));
check('unsupported EV question does not recommend', () => { noPicks('Are electric cars waterproof?'); assert.match(reply('Are electric cars waterproof?').text, /cannot reliably/); });
check('unsupported named question is explicit', () => assert.match(reply('Can Nexon fly?').text, /cannot reliably answer/));
console.log(`\n${passed} assistant checks passed${process.exitCode ? '; failures above' : ''}.`);
