"use client";

import { useMemo, useState } from "react";
import { Battery, Calculator, Gauge, IndianRupee } from "lucide-react";

const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number.isFinite(value) ? value : 0);
const bounded = (value: number, min = 0) => Math.max(min, Number.isFinite(value) ? value : min);

function NumberField({ label, value, onChange, min = 0, max, step = 1, suffix }: { label: string; value: number; onChange: (value: number) => void; min?: number; max?: number; step?: number; suffix?: string }) {
  return <label><span className="text-xs font-semibold text-slate-300">{label}</span><span className="mt-2 flex min-h-12 items-center rounded-xl border border-white/10 bg-slate-950/70 px-3 focus-within:border-sky-300/40"><input type="number" value={value} min={min} max={max} step={step} onChange={(event) => onChange(bounded(Number(event.target.value), min))} className="min-w-0 flex-1 bg-transparent text-base font-semibold outline-none" /><span className="ml-2 text-xs text-slate-500">{suffix}</span></span></label>;
}

function Result({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/10 bg-slate-950/60 p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.15em] text-slate-500">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p></div>; }
function Tool({ id, icon: Icon, title, copy, children, formula }: { id: string; icon: typeof Calculator; title: string; copy: string; children: React.ReactNode; formula: string }) { return <section id={id} className="scroll-mt-24 overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.04]"><div className="flex gap-4 p-5 sm:p-7"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl bg-sky-400/10 text-sky-300"><Icon className="h-5 w-5" /></span><div><h2 className="text-2xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{copy}</p></div></div><div className="border-t border-white/10 p-5 sm:p-7">{children}<p className="mt-5 rounded-xl border border-emerald-300/15 bg-emerald-300/[0.06] px-4 py-3 text-xs leading-5 text-emerald-100"><strong>Formula:</strong> {formula}</p></div></section>; }

export default function DecisionCalculators() {
  const [price, setPrice] = useState(1800000), [down, setDown] = useState(300000), [rate, setRate] = useState(9), [months, setMonths] = useState(60);
  const emi = useMemo(() => { const principal = Math.max(0, price - down); const monthlyRate = rate / 1200; const payment = monthlyRate === 0 ? principal / Math.max(1, months) : principal * monthlyRate * (1 + monthlyRate) ** months / ((1 + monthlyRate) ** months - 1); return { principal, payment, interest: payment * months - principal }; }, [price, down, rate, months]);
  const [annualKm, setAnnualKm] = useState(15000), [evKmKwh, setEvKmKwh] = useState(6.5), [homeShare, setHomeShare] = useState(80), [homeRate, setHomeRate] = useState(9), [publicRate, setPublicRate] = useState(20), [petrolKmL, setPetrolKmL] = useState(15), [petrolRate, setPetrolRate] = useState(105);
  const running = useMemo(() => { const blend = homeRate * Math.min(100, homeShare) / 100 + publicRate * (100 - Math.min(100, homeShare)) / 100; const ev = annualKm / Math.max(.1, evKmKwh) * blend; const petrol = annualKm / Math.max(.1, petrolKmL) * petrolRate; return { blend, ev, petrol }; }, [annualKm, evKmKwh, homeShare, homeRate, publicRate, petrolKmL, petrolRate]);
  const [usableKwh, setUsableKwh] = useState(45), [observedEfficiency, setObservedEfficiency] = useState(6), [start, setStart] = useState(90), [reserve, setReserve] = useState(15), [adjustment, setAdjustment] = useState(10);
  const range = useMemo(() => { const full = usableKwh * observedEfficiency; const beforeConditions = full * Math.max(0, Math.min(100, start - reserve)) / 100; return { full, usable: beforeConditions * (1 - Math.min(100, adjustment) / 100) }; }, [usableKwh, observedEfficiency, start, reserve, adjustment]);
  const [referenceCapacity, setReferenceCapacity] = useState(45), [reportedCapacity, setReportedCapacity] = useState(42), [reportOdometer, setReportOdometer] = useState(30000);
  const capacity = reportedCapacity / Math.max(.1, referenceCapacity) * 100;
  const [offer, setOffer] = useState(900000), [loanBalance, setLoanBalance] = useState(150000), [repairs, setRepairs] = useState(20000), [transfer, setTransfer] = useState(5000);
  const netSale = Math.max(0, offer - loanBalance - repairs - transfer);

  return <div className="mx-auto grid max-w-7xl gap-7 px-4 py-12 sm:px-6 sm:py-16 lg:px-8">
    <nav aria-label="Calculator shortcuts" className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[["#emi","EMI"],["#running-cost","Running cost"],["#range","Range"],["#capacity","Battery & resale"]].map(([href,label]) => <a key={href} href={href} className="flex min-h-12 items-center justify-center rounded-xl border border-white/10 bg-white/[0.04] px-3 text-center text-sm font-semibold hover:bg-white/[0.08]">{label}</a>)}</nav>

    <Tool id="emi" icon={IndianRupee} title="EV loan EMI calculator" copy="Enter the lender’s actual quoted rate and charges separately. This is a mathematical repayment estimate, not a loan offer." formula="EMI = P × r × (1+r)ⁿ ÷ ((1+r)ⁿ−1), where P is financed principal and r is the monthly interest rate.">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="On-road price" value={price} onChange={setPrice} step={10000} suffix="₹" /><NumberField label="Down payment" value={down} onChange={setDown} step={10000} suffix="₹" /><NumberField label="Annual interest rate" value={rate} onChange={setRate} step={0.1} max={40} suffix="%" /><NumberField label="Loan tenure" value={months} onChange={(value) => setMonths(Math.round(value))} min={1} max={120} suffix="months" /></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3"><Result label="Financed principal" value={money(emi.principal)} /><Result label="Estimated monthly EMI" value={money(emi.payment)} /><Result label="Total interest" value={money(emi.interest)} /></div><p className="mt-4 text-xs leading-5 text-slate-500">Excludes processing fees, insurance, late charges, floating-rate changes and lender-specific rounding. Confirm the repayment schedule with the lender.</p>
    </Tool>

    <Tool id="running-cost" icon={Calculator} title="EV vs petrol running cost" copy="Use your observed efficiency and actual local tariffs. The home/public charging mix is visible and adjustable." formula="Annual energy cost = annual distance ÷ observed efficiency × blended energy price.">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Distance per year" value={annualKm} onChange={setAnnualKm} step={1000} suffix="km" /><NumberField label="EV observed efficiency" value={evKmKwh} onChange={setEvKmKwh} step={.1} suffix="km/kWh" /><NumberField label="Home charging share" value={homeShare} onChange={setHomeShare} max={100} suffix="%" /><NumberField label="Home electricity rate" value={homeRate} onChange={setHomeRate} step={.5} suffix="₹/kWh" /><NumberField label="Public charging rate" value={publicRate} onChange={setPublicRate} step={.5} suffix="₹/kWh" /><NumberField label="Petrol efficiency" value={petrolKmL} onChange={setPetrolKmL} step={.5} suffix="km/l" /><NumberField label="Petrol price" value={petrolRate} onChange={setPetrolRate} step={.5} suffix="₹/l" /></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-3"><Result label="Blended EV energy rate" value={`₹${running.blend.toFixed(2)}/kWh`} /><Result label="EV energy per year" value={money(running.ev)} /><Result label="Petrol fuel per year" value={money(running.petrol)} /></div><p className="mt-4 text-xs leading-5 text-slate-500">Energy-only comparison. It excludes purchase price, charging losses, maintenance, insurance, finance and resale; use PlugV’s TCO calculator for those assumptions.</p>
    </Tool>

    <Tool id="range" icon={Gauge} title="Evidence-based range planner" copy="Use usable battery capacity and efficiency you observed over representative driving—not an advertised best case." formula="Reserve-adjusted range = usable kWh × observed km/kWh × available charge percentage × your condition adjustment.">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5"><NumberField label="Usable battery capacity" value={usableKwh} onChange={setUsableKwh} step={.1} suffix="kWh" /><NumberField label="Observed efficiency" value={observedEfficiency} onChange={setObservedEfficiency} step={.1} suffix="km/kWh" /><NumberField label="Starting charge" value={start} onChange={setStart} max={100} suffix="%" /><NumberField label="Arrival reserve" value={reserve} onChange={setReserve} max={100} suffix="%" /><NumberField label="Your condition reduction" value={adjustment} onChange={setAdjustment} max={100} suffix="%" /></div>
      <div className="mt-5 grid gap-3 sm:grid-cols-2"><Result label="Observed full-charge range" value={`~${Math.round(range.full)} km`} /><Result label="Range after reserve & adjustment" value={`~${Math.round(range.usable)} km`} /></div><p className="mt-4 text-xs leading-5 text-slate-500">Set the reduction from your own experience for weather, AC, speed, traffic, elevation and payload. PlugV does not claim a universal factor for these conditions.</p>
    </Tool>

    <Tool id="capacity" icon={Battery} title="Battery capacity record" copy="Record an OEM or authorised-service diagnostic. This calculator does not infer health from dashboard range or charging energy." formula="Reported capacity percentage = service-reported usable capacity ÷ the same model/variant’s reference usable capacity × 100.">
      <div className="grid gap-4 sm:grid-cols-3"><NumberField label="OEM reference usable capacity" value={referenceCapacity} onChange={setReferenceCapacity} step={.1} suffix="kWh" /><NumberField label="Service-reported usable capacity" value={reportedCapacity} onChange={setReportedCapacity} step={.1} suffix="kWh" /><NumberField label="Odometer at report" value={reportOdometer} onChange={setReportOdometer} step={1000} suffix="km" /></div>
      <div className="mt-5"><Result label="Reported capacity vs reference" value={`${capacity.toFixed(1)}% at ${reportOdometer.toLocaleString("en-IN")} km`} /></div><p className="mt-4 text-xs leading-5 text-amber-100">Not a battery diagnosis or warranty decision. Confirm what the diagnostic metric means with the manufacturer; reference and reported values must use the same definition.</p>
    </Tool>

    <Tool id="resale" icon={IndianRupee} title="Verified resale offer comparison" copy="Calculate net proceeds from a real written offer. PlugV does not predict a future market price." formula="Net proceeds = written offer − outstanding loan − agreed repairs − transfer and transaction costs.">
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><NumberField label="Written buyer offer" value={offer} onChange={setOffer} step={10000} suffix="₹" /><NumberField label="Outstanding loan" value={loanBalance} onChange={setLoanBalance} step={10000} suffix="₹" /><NumberField label="Agreed repair costs" value={repairs} onChange={setRepairs} step={1000} suffix="₹" /><NumberField label="Transfer/transaction costs" value={transfer} onChange={setTransfer} step={500} suffix="₹" /></div>
      <div className="mt-5"><Result label="Estimated net proceeds" value={money(netSale)} /></div><p className="mt-4 text-xs leading-5 text-slate-500">Verify lender foreclosure figures, ownership-transfer requirements and payment clearance before handing over the vehicle.</p>
    </Tool>
  </div>;
}
